### PR TITLE
Customisations for Intel QuickSync encoding

### PR DESCRIPTION
**Pull request by mjb2000**
Customisations to quality, bitrate, framesize and scaling method

### CODE REVIEW

**Comment by mjb2000** [comment]
Hi Luke

Can you take a look at these changes, they are working nicely for  me.

I was not able to make suitable tweaks within FFMPEG (in particular trying to override the frame size within the QSV encoder caused a lot of strange results - I think because the rest of FFMPEG expected the original values to be used and not my overridden values).
### Questions
I've made a couple of other tweaks too and have a couple of questions...
#### CRF
I'm not using CRF based encoding - In most documents I've read, since we are streaming at a particular bit-rate the most important thing is the bit-rate. Therefore the setting that should be changed to affect quality should be the `-preset`. The slower the preset the better the quality will be at the specific bit-rate. 

This could mean low end CPUs may not be able to keep up, but this is why I would have thought it would make sense to use `ultrafast | fast | slower` as the options that change when the user selects a quality.
#### Rounding factor
I have added some logic to use a different rounding factor if using QSV. Based on the code I've added, the values for any other codec should remain unchanged.
#### Maxrate confusion
I noticed here:
```
// H264
                if (hasFixedResolution)
                {
                    if (isHls)
                    {
                        return string.Format(" -b:v {0} -maxrate ({0}*.80) -bufsize {0}", bitrate.Value.ToString(UsCulture));
                    }
```
That the `-maxrate` would be less than the bitrate when we have an HLS stream, in my edit I have set the h264_qsv `-maxrate` to be 20% higher than the bitrate because - but have I overlooked something here?
#### Scaling method
Finally, you'll notice I have added a scaling method which will be appended to the existing scaling options - `:flags=fast_bilinear` - This is because I found that with the default method I was getting about 25fps with low CPU and GPU utilization (something was clearly not working correctly).

After switching to this different scaling method, I was getting about 55fps with 75% GPU and 85% CPU utilization

**Comment by jabbera** [comment]
I was checking out your changes and it looks like the nvec one includes a bunch of merges from dev. I'm guessing you were trying to update your branch to the current dev version? What git commands did you use?

**Comment by mjb2000** [comment]
Yeah - I get really confused with git commands. There was an miss-match
after Luke change some things whilst I was implementing the original QS
things, and I didn't really know what I should be doing. Apologies.

Are you able to point be in the right direction for how I should fix this?
Or are you able to implement the NVENC changes without me fixing my git
mistakes?

M



Matt Bunce | 0789 0788 321 | matt@purplepixelmedia.co.uk



Purple Pixel Media Ltd, 28 Vanguard Close, High Wycombe, HP12 3FP |
Registered company: 06438677

**Comment by jabbera** [comment]
I don't know about fixing your branch. It's pretty mangled. What I can do is tell you the proper way to rebase your changes onto a branch.

First you should ALWAYS work off a new branch. In this case you should be working off of the dev branch but with a new branch name. After your initial fetch open up a git shell and run the following (omit everything after \\ it's meant to be commentary:

git co dev \\change to the dev brach
git branch YourNewBranchNameHere \\ create a new branch
git co  YourNewBranchNameHere \\ change to the new branch
git push --set-upstream origin YourNewBranchNameHere \\ push the branch to your remote repo

At this point you have a new branch called: YourNewBranchNameHere that is based on current dev. Do all of your work in this branch then submit a pull request. If it's accepted there is nothing else to do. 

However, dev continues to change while your pull request sits there. At some point you need to integrate the dev changes into your branch so your pull request can be merged. The first thing you need to do is get the dev changes into your local repo.

git fetch upstream \\ bring in changes from the official media browser repo
git co dev \\ change to your dev branch
git merge upstream/dev \\ merge the changes from the official repo into your local dev repo
                                       \\ since no changes were made to the dev branch because all work
                                       \\ was done in YourNewBranchNameHere this will merge conflict free
git push \\ sync to your remote repo

At this point you have a local dev branch that mirrors the official media browser branch. You now want to bring those changes into YourNewBranchNameHere. But the result you want is your new changes replayed ontop of the dev changes so they can be easily merged.

git co YourNewBranchNameHere  \\ change to your new branch name
git rebase dev \\ This is what does the magic. 

The command git rebase dev will unwind any of your changes merge in the changes from dev into YourNewBranchNameHere then attempt to replay your changes on top. If there are no contlicts you can just do a git push and you are done.

If there are merge conflict you will need to fix them. They are marked with the standard git conflict resolution markers. Then run:

git add [Conflict files] \\ Each file with a conflict needs to be re-added individually after resolution.
git rebase --continue \\ signal all conflicts are dealt with.
git push -f \\ you need to force since this is a non continuous change.

If you have any questions feel free to ask, but I recommend creating a new branch and just re-doing your work there.

**Comment by mjb2000** [comment]
Thanks Mike

This is really helpful. I'll see if I can clean things up - It looks at
though my key problem was the fact that I was using the Dev branch.

M



Matt Bunce | 0789 0788 321 | matt@purplepixelmedia.co.uk



Purple Pixel Media Ltd, 28 Vanguard Close, High Wycombe, HP12 3FP |
Registered company: 06438677

**Comment by jabbera** [comment]
I have an ulterior motive. Once this is done I can finally move to a low powered server instead of my i7 beast.

**Comment by mjb2000** [comment]
haha - Well that was always my motivation!

I started out with the low-power chip and had to make QS work to allow
transcoding at all!

It does seem to be working pretty well for me. Haven't done heaps of
testing, but seems to be working for most of my needs. Once the few issues
with QS + LibAV are resolved it should be even better.

What CPU are you looking to move to?

M



Matt Bunce | 0789 0788 321 | matt@purplepixelmedia.co.uk



Purple Pixel Media Ltd, 28 Vanguard Close, High Wycombe, HP12 3FP |
Registered company: 06438677

**Comment by jabbera** [comment]
I don't have a plan yet. I just know my 1000 watt gaming pc is totally overpowered:-)

**Comment by mjb2000** [comment]
Well, I've said it many times on the forum, but I am a big fan of the
Baytrail chips. I used the J1900, but the J2900 is slightly more powerful.
They use very little power (10W rated - I power it with a 400W PSU along
with a twin DVB-S2 PCIx card, SSD and 3.5" HDD - It draws around 17W idle
and 24W under load as measured at the wall).



Matt Bunce | 0789 0788 321 | matt@purplepixelmedia.co.uk



Purple Pixel Media Ltd, 28 Vanguard Close, High Wycombe, HP12 3FP |
Registered company: 06438677

**Comment by LukePulverenti** [comment]
If you guys think GStreamer would be better, we can look at it. It looks like it will support more operating systems and hardware. It would be a big job to switch from ffmpeg but we could try to do it little by little.

**Comment by jabbera** [comment]
I've done some reading about gstreamer and am skeptical. It doesn't seem to support nvenc or quick sync yet, but I like the concept. Information is hard to come by though

**Comment by mjb2000** [comment]
Hi Mike 

Thanks again for your help, I have now created my own GPU transcoding branch, and submitted a new pull request with the latest changes.

M

**Pull request closed without merging**
