### PR TITLE
Ssl in mediabrowser against new listener.

### PR DESCRIPTION
**Pull request by jabbera**
Can't change pull request target branch apparently. (Or I couldn't figure out how.)

This has been updated to allow certificate to be configurable, although it's hard coded right now. Will update the UI once the internals have been decided on\approved.

Whats the UDP port used for?

### CODE REVIEW

**Comment by jabbera** [comment]
What are the advantages of using the native web socket listener instead of SocketHttpListener listener? While ssl is certainly supported the netsh hoops you need to jump through make it PAINFUL:-)

**Comment by LukePulverenti** [comment]
you don't have to worry about that. it will be deprecated over the next couple of releases.

**Comment by jabbera** [comment]
Great.

**Comment by jabbera** [comment]
HTML changes. I have no idea what I'm doing. Just copy and pasted some related fields.

**Comment by LukePulverenti** [comment]
I made some changes prior to the stable release to get the https port property added and get the ball rolling on getting the port authorized for all new users via the initial admin prompt. You'll need to update this to use that so that the pull request can be merged in automatically.

Also, deprecating the WebSocketPortNumber property is good, but we can't do it yet because it will likely break the iOS app. So that needs to be restored temporarily, just have it point to the http port.

**Comment by jabbera** [comment]
Rebased. Can't test from where I am though.

**Comment by LukePulverenti** [comment]
need to update again and re-submit (sorry). once you do that i'll try to merge it in this weekend so we can start testing. thanks.

**Comment by LukePulverenti** [comment]
also just for consistency can you rename CertificateLocation to CertificatePath in all places? thanks.

**Comment by jabbera** [comment]
All set.

**Pull request merged**
