### PR TITLE
Add poster image to video player

### PR DESCRIPTION
**Pull request by tadams88**

### CODE REVIEW

**Comment by tadams88** [comment]
@LukePulverenti this is getting an intermittent 500 error requesting the backdrop image from the server... the error is:

The process cannot access the file '{serverLocation}\cache\images\resized-images\c\c95258cf-d143-0c40-3a91-1518eacab4a5.webp' because it is being used by another process.

My guess is the process that returned the backdrop for the details page hasn't been terminated/released the file?

**Comment by tadams88** [comment]
The intermittent 500 from the server serving the image is hitting the video error handling, which stops the video and brings up a popup. This is pretty nasty behavior. Closing this pull request until I can fix the image serving, or figure out a way to detect that the error came from the poster and just ignore it in the error handling...

**Comment by tadams88** [comment]
I've been using this for a week and have not been able to recreate the errors I was seeing the first night. Seems stable.

**Comment by LukePulverenti** [comment]
Awesome. Just sync up this pull with the latest code and then i'll merge it in.

**Comment by tadams88** [comment]
Synced.

**Pull request merged**
